/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ad_data_constants.h"

namespace interface { namespace ad_data {

const ad_dataConstants g_ad_data_constants;

ad_dataConstants::ad_dataConstants() {
}

}} // namespace

