/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ad_data_CONSTANTS_H
#define ad_data_CONSTANTS_H

#include "ad_data_types.h"

namespace interface { namespace ad_data {

class ad_dataConstants {
 public:
  ad_dataConstants();

};

extern const ad_dataConstants g_ad_data_constants;

}} // namespace

#endif
