/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ad_event_CONSTANTS_H
#define ad_event_CONSTANTS_H

#include "ad_event_types.h"

namespace interface { namespace ad_event {

class ad_eventConstants {
 public:
  ad_eventConstants();

};

extern const ad_eventConstants g_ad_event_constants;

}} // namespace

#endif
