/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ad_event_constants.h"

namespace interface { namespace ad_event {

const ad_eventConstants g_ad_event_constants;

ad_eventConstants::ad_eventConstants() {
}

}} // namespace

