/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Adaptive_constants.h"

namespace interface { namespace adaptive {

const AdaptiveConstants g_Adaptive_constants;

AdaptiveConstants::AdaptiveConstants() {
}

}} // namespace

