/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Adaptive_CONSTANTS_H
#define Adaptive_CONSTANTS_H

#include "Adaptive_types.h"

namespace interface { namespace adaptive {

class AdaptiveConstants {
 public:
  AdaptiveConstants();

};

extern const AdaptiveConstants g_Adaptive_constants;

}} // namespace

#endif
