/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "biz_data_constants.h"

namespace interface { namespace biz_data {

const biz_dataConstants g_biz_data_constants;

biz_dataConstants::biz_dataConstants() {
}

}} // namespace

