/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef biz_data_CONSTANTS_H
#define biz_data_CONSTANTS_H

#include "biz_data_types.h"

namespace interface { namespace biz_data {

class biz_dataConstants {
 public:
  biz_dataConstants();

};

extern const biz_dataConstants g_biz_data_constants;

}} // namespace

#endif
