/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef datatypes_TYPES_H
#define datatypes_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace interface { namespace constants { namespace datatypes {

typedef int32_t adaptive_int;

typedef adaptive_int Timestamp;

typedef adaptive_int UserID;

typedef adaptive_int BizID;

typedef adaptive_int AdID;

typedef adaptive_int AdReqID;

typedef adaptive_int AdPosition;

}}} // namespace

#endif
