/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "datatypes_constants.h"

namespace interface { namespace constants { namespace datatypes {

const datatypesConstants g_datatypes_constants;

datatypesConstants::datatypesConstants() {
}

}}} // namespace

