/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef datatypes_CONSTANTS_H
#define datatypes_CONSTANTS_H

#include "datatypes_types.h"

namespace interface { namespace constants { namespace datatypes {

class datatypesConstants {
 public:
  datatypesConstants();

};

extern const datatypesConstants g_datatypes_constants;

}}} // namespace

#endif
