/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "exceptions_constants.h"

namespace interface { namespace constants { namespace error_codes {

const exceptionsConstants g_exceptions_constants;

exceptionsConstants::exceptionsConstants() {
  ErrorDescription.insert(std::make_pair((ErrorCode::type)0, "Unknown error"));

}

}}} // namespace

