/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef exceptions_CONSTANTS_H
#define exceptions_CONSTANTS_H

#include "exceptions_types.h"

namespace interface { namespace constants { namespace error_codes {

class exceptionsConstants {
 public:
  exceptionsConstants();

  std::map<ErrorCode::type, std::string>  ErrorDescription;
};

extern const exceptionsConstants g_exceptions_constants;

}}} // namespace

#endif
