/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Makefile_constants.h"



const MakefileConstants g_Makefile_constants;

MakefileConstants::MakefileConstants() {
}



