/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Makefile_CONSTANTS_H
#define Makefile_CONSTANTS_H

#include "Makefile_types.h"



class MakefileConstants {
 public:
  MakefileConstants();

};

extern const MakefileConstants g_Makefile_constants;



#endif
