/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef user_attributes_TYPES_H
#define user_attributes_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace interface { namespace constants { namespace user_attributes {

struct Gender {
  enum type {
    UNKNOWN = 0,
    MALE = 1,
    FEMALE = 2,
    OTHER = 3
  };
};

extern const std::map<int, const char*> _Gender_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const Gender::type& val);

struct DeviceType {
  enum type {
    UNKNOWN = 0,
    COMPUTER = 1,
    MOBILE = 2
  };
};

extern const std::map<int, const char*> _DeviceType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const DeviceType::type& val);

}}} // namespace

#endif
