/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef user_attributes_CONSTANTS_H
#define user_attributes_CONSTANTS_H

#include "user_attributes_types.h"

namespace interface { namespace constants { namespace user_attributes {

class user_attributesConstants {
 public:
  user_attributesConstants();

};

extern const user_attributesConstants g_user_attributes_constants;

}}} // namespace

#endif
