/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "user_data_constants.h"

namespace interface { namespace user_data {

const user_dataConstants g_user_data_constants;

user_dataConstants::user_dataConstants() {
}

}} // namespace

