/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef user_data_CONSTANTS_H
#define user_data_CONSTANTS_H

#include "user_data_types.h"

namespace interface { namespace user_data {

class user_dataConstants {
 public:
  user_dataConstants();

};

extern const user_dataConstants g_user_data_constants;

}} // namespace

#endif
