/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "user_attributes_constants.h"

namespace interface { namespace constants { namespace user_attributes {

const user_attributesConstants g_user_attributes_constants;

user_attributesConstants::user_attributesConstants() {
}

}}} // namespace

