#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class Gender(object):
    UNKNOWN = 0
    MALE = 1
    FEMALE = 2
    OTHER = 3

    _VALUES_TO_NAMES = {
        0: "UNKNOWN",
        1: "MALE",
        2: "FEMALE",
        3: "OTHER",
    }

    _NAMES_TO_VALUES = {
        "UNKNOWN": 0,
        "MALE": 1,
        "FEMALE": 2,
        "OTHER": 3,
    }


class DeviceType(object):
    UNKNOWN = 0
    COMPUTER = 1
    MOBILE = 2

    _VALUES_TO_NAMES = {
        0: "UNKNOWN",
        1: "COMPUTER",
        2: "MOBILE",
    }

    _NAMES_TO_VALUES = {
        "UNKNOWN": 0,
        "COMPUTER": 1,
        "MOBILE": 2,
    }
fix_spec(all_structs)
del all_structs
